language: node_js
sudo: required
dist: trusty
os: linux
node_js:
- v6.10.0
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- |
  sudo apt-get install wget
  wget https://saucelabs.com/downloads/sc-4.4.6-linux.tar.gz
  tar -zxvf sc-4.4.6-linux.tar.gz
  sudo chmod u+x sc-4.4.6-linux/bin/sc
  ./sc-4.4.6-linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -f sauce-connect-ready-16721 -l /home/travis/sauce-connect.log > /dev/null 2>&1 &
  sleep 30
script:
- npm run test
env:
  global:
  - secure: JzIuQtuvBgVLFIIuZ2QQ1LNs0kmHHOWyud6dTfqPJXrdSFh9+U2XZ0xrFflUjRsFpJd7EK3bnFBfM9zE0216lVb9ZKV93mhdoxSLoYipZh3hGx01KXPhwVBbI3AiDS6EXxg2kS/W2eIVXZMiCE1uhR4zpRmVv5FnXXXEd/PIgS6OlwWYuBSM0hYpLru+0mpusyTMxG43ADOQLJXokvqJr73LmQaz9MBvO5WMQT5f87PEuH0qzJSephzZH7Z3+Un/EmsELihJBItwxn+orn6q8a+3Fq0IBt9BXXhduGYEj8rLuW/15gRQ6KlRerMaLLl0G/vmT29yY4MiSn/S7m+PMRhAbHXzRn/OKCek6cSIA4KnZUtb3M9AM+alubf31OAr4jEUtgXMxcmZAkoa7PUI/UfGqY6KuGwpfXReQMs4BDYiKCmFGDOuLlmwiQGODANiGTc+kbxZfB21Wwxs4SEjSI+jY0/HnWCLeeyVr2NXeu6COrEk6ixGI8PrQAZhPFRAz76y/jMuyVrrvACRhUoYgV4FvREdr7XXCkVzTXF96pPDNmxOQHARuV6ZutHQVFubDkgCB3u/+ewj0Xlt06CTPX/l4ZMOKHT/XDyg+bDWSpzD9chENMZxA4jC2ZLMZzxR77U6ibp2nkdb6D6Im1l4hr4+KHrPOK3DVFC4OKPdFnM=
  - secure: HMAopDlYrEqkUwdvJV59W7hkboW/ZukSovVyA/nDxzcoSa355KL8hbtJAtLX8JVFadP17fbSu8dYpBB/QBJjPB6nQD8XLdW0ik98i4NC/8DbFuILyqR4p2uibLbJ84gM3Cs5whEUt99Y6QzMIOzvE9QlNnk8pYpf0lk58NlLgDOhnjZDOX5wfQjdRwXvgIEFGlFt8S9eiD7KOW1hNRy4qDzhZHzX3+2Y5JKbazrKIlcMSQBL/foA8+6kKMZVb3UxaxVHSC1BBSIJwikzkRI1O8lnIyRkHjCrE1oO1w+h1gq6snGDSEdKjRKD45AfV2/GLguudS9APocMHndclpZJVYgVP593SRRJzeIkTm0drnwBXTPEcSG9xCG2MEx8x/ezA30jC4uYvdFS05k6b4Sr7Ubsgg/LnxajiNf2fgqxxxr4y6gEVcux07kyqsngBrkAnWyuwyn4Y07i6lIfoh0eOLjw7cy4qy+jJhX2E+Dfbc49GOuDLcSZe+Bfq9hnVPnGRtMccMO3WVxhuWOCQCK83S92OCdXyynmPogEMMM98Os+/y0DtJ6GzpmDM6W7a5DOpyS/dODMQ2EfH3hYomZNWZEzpTGtw95p5IrDhn5XDYWNc71svcfL1p1b1OBLn1czAa3g2KHdUcXK/EqGoyKBO0FAbH/7JYdQ/enSpG+Q6o8=
